server:
  servlet:
    encoding:
      force-response: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://movie-recommendation.kro.kr:3306/sfdb
    username: sf
    password: rkseksgkwksk
jwt:
  token:
    secret: hello.world.ee.ff
